### ISSUE TITLE
/stop can start again

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/command-start-stop#69]
example 

https://github.com/ubiquity/ts-template/issues/61#issuecomment-2440188077

Calling stop should not penalize. If they called stop they should be able to reassign in the future becauss its not a disqualification.

**Comment by ishowvel** [comment]
the specification seems pretty straight forward

**Comment by ishowvel** [comment]
i have noticed that only 1 plugin works in the kernel at the time, my pricing plugin doesnt work when i add this start stop plugin to the .ubiquity-os config, the kernel only forwards the payload to one plugin for some reason

**Comment by ishowvel** [comment]
this may already be implemented

**Comment by ishowvel** [comment]
the kernel doesnt even know if these plugins exist

**Comment by 0x4007** [comment]
My best guess is that you have a formatting problem in your yml config. Sometimes it's difficult to get the indentations perfectly.

**Comment by gentlementlegen** [comment]
It is trying to forward it but what it received is not a valid command like `/label`. Plugins react only to certain events / inputs.

**Comment by ishowvel** [comment]
Shouldn't it receive the valid commands for this plugin ie /start, /stop

**Comment by gentlementlegen** [comment]
In the configuration file you gave, you chained plugins so it won't. You need to change it to something like
```yaml
plugins:
  - uses:
    - plugin: http://127.0.0.1:4000
      with:
        labels:
          time:
            - "Time: <15 Minutes"
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
            - "Time: <2 Weeks"
            - "Time: <1 Month"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 2
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  -  uses:
    - plugin: ishowvel/daemon-disqualifier:compute.yml@testing
      with:
        disqualification: "2 minutes"
        warning: "1 minutes"
        watch:
          optOut:
            - "repoName"
            - "repoName2"
        eventWhitelist:
          - "review_requested"
          - "ready_for_review"
          - "commented"
          - "committed"
  - uses:
    - plugin: http://localhost:4001 # or the URL where the plugin is hosted
      name: start-stop
      id: start-stop-command
      description: "Allows a user to start/stop a task without negative XP impact"
      command: "\/start|\/stop"
      example: "/start" # or "/stop"
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "30 Days"
        maxConcurrentTasks: # Default concurrent task limits per role.
          member: 5
          contributor: 3
        startRequiresWallet: true # default is true
        emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
        rolesWithReviewAuthority: ["MEMBER", "OWNER"]
    
```

so every plugin is called individually.
