### ISSUE TITLE
New config property `requiredLabelsToStart`

### ISSUE THREAD

**Issue by rndquu** [ubiquity-os-marketplace/command-start-stop#79]
Right now our main goal is to show investors that the project is capable of generating a revenue. 

So basically we need to concentrate on tasks related to:
1. Partner onboarding (i.e. [UbiquityOS Marketplace GUI](https://github.com/ubiquity-os/ubiquity-os-plugin-installer))
2. Charging fees
3. Making the kernel stable
4. Making core plugins stable

We have the following organizational issues right now:
1. All core team members are doing everything with a lack of focus. 
2. There's too much PRs to review (from outside contributors) and none-important issues (that don't "move the needle") to discuss.

For example check these issues:
- https://github.com/ubiquity-os/ubiquity-os-kernel/issues/180
- https://github.com/ubiquity-os/ubiquity-os-kernel/issues/154

Although both of the issues above have the "Priority: 3 (High)" label in reality their business value is 1 (on a scale from 1 to 4). **The "Priority" label must reflect a business priority, not a development one.**

As a part of this issue we should add a new property `requiredLabelsToStart` which accepts an array of labels required to call the `/start` command.

Example config:
```
- plugin: http://localhost:4000 # or the URL where the plugin is hosted
  name: start-stop
  id: start-stop-command
  command: "\/start|\/stop"
  with:
    requiredLabelsToStart: ["Priority: 3 (High)", "Priority: 4 (Urgent)", "Priority: 5 (Emergency)"]
    # ...other props
```

In the example above it will be possible to start an issue only if it has required business priority labels.

When current issue is finished we'll:
1. Review all github issues and update the "Priority" label to reflect a business value
2. Set `requiredLabelsToStart: ["Priority: 3 (High)", "Priority: 4 (Urgent)", "Priority: 5 (Emergency)"]` for all of our organizations

This way we:
1. Shift core team focus only on issues that have a business impact
2. Reduce number of PRs to review and issues to discuss (because outside contributors will have to solve only high business priority issues)
3. Save money and time only to what matters
